### PR TITLE
Fixed view of Redirection and Subscription Pages for Mobile

### PR DESCRIPTION
**Pull request by knit-pay**
Fixed view of Redirection and Subscription Pages for mobile phones.

### CODE REVIEW

**Comment by remcotolsma** [comment]
Thanks.

**Before:**

Scherm­afbeelding 2024-01-11 om 14 40 15

**After:**

Scherm­afbeelding 2024-01-11 om 14 40 41

**Comment by rvdsteege** [comment]
The card number is not displayed anymore in the _after_ screenshot and the button seems to large? 😕 I think this needs some further attention?

**Comment by knit-pay** [comment]
@rvdsteege @remcotolsma 
Thanks for bringing these issues to my notice. I will check this further.

**Comment by knit-pay** [comment]
Hello @rvdsteege and @remcotolsma 

Made changes in CSS, and now the button and card number are looking better. Please check.

image

**Comment by knit-pay** [comment]
Hello @rvdsteege and @remcotolsma

had you got chance to review the changes?

**Comment by knit-pay** [comment]
Thanks @rvdsteege and @remcotolsma for considering this contribution.

**Pull request merged**
